name: Android CI Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit test with gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: ./gradlew assembleRelease
    - name: 'upload artifact'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: build.tar.gz
          path: app/build/outputs/apk/release/magic-up.apk
