name: Android CI Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create release apk
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: ./gradlew assembleRelease
    - name: 'upload artifact'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: magic-up.apk
        path: app/build/outputs/apk/release/magic-up.apk
    - uses: ncipollo/release-action@v1
      name: 'generate release'
      with:
        artifact: "app/build/outputs/apk/release/magic-up.apk"
        body: "TODO: Add release notes"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
